# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: MyAgentPool

stages:
- stage: InstallDependencies
  jobs:
  - job: InstallDependencies
    displayName: 'Install Node.js and Dependencies'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - script: 
        npm remove node_modules
        npm remove package-lock.json
        npm install
      displayName: 'npm install'

- stage: Test
  jobs:
  - job: RunTests
    steps:
    - script: 
        npm install --save-dev cross-env
        npm run test
      displayName: 'Run Unit Tests'

- stage: Build
  jobs:
  - job: Build
    displayName: 'Build Application'
    steps:
    - script: 
        npm install --save-dev cross-env
        npm run build
      displayName: 'npm run build'

- stage: Dockerize
  jobs:
  - job: BuildDockerImage
    steps:
    - script: 
        docker build -t project-app .
        docker tag project-app janakorayem/my-project-app:latest
        docker push janakorayem/myproject:project-app
      displayName: 'Build and Push Docker Image'

- stage: DeployToAWS
  jobs:
  - job: Deploy
    steps:
    - task: UsePythonVersion@0
      inputs:
         versionSpec: '3.x'
         addToPath: true
    - script: 
       ssh -i "projectt.pem" ubuntu@ec2-52-204-236-242.compute-1.amazonaws.com 'bash -s' < ./scripts/deploy.sh
    displayName: 'Deploy to AWS EC2 Instance'





